from app.models.usuario import Usuario  
from app.models.categoria import Categoria  
from app.models.recinto import Recinto  
from app.models.evento import Evento  
from app.models.zona import Zona  
from app.models.cupon_descuento import CuponDescuento 
from app.models.orden import Orden 
from app.models.detalle_orden import DetalleOrden  
from app.models.boleto import Boleto 
from app.models.carrito_compra import CarritoCompra  
